# Generated by Django 4.0.3 on 2022-05-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0004_remove_customuser_profile_pic_customuser_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='monthly_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
