# Generated by Django 4.0.3 on 2022-05-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_monthly_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='next_monthly_reset',
            field=models.DateTimeField(null=True),
        ),
    ]
