# Generated by Django 4.0.4 on 2022-05-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_next_monthly_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='monthly_deposit_left',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='current_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='monthly_limit',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='total_earnings',
            field=models.FloatField(default=0.0),
        ),
    ]
