# Generated by Django 4.0.3 on 2022-05-03 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_monthly_deposit_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friend_requests',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
