# Generated by Django 4.0.4 on 2022-05-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0008_customuser_friend_requests_customuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_session',
            field=models.TextField(default=''),
        ),
    ]
