# Generated by Django 4.0.3 on 2022-04-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_added',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
